In [1]:
# this contains various notes about test statistics, hypothesis testing,
# p-values, null and alternative testing, iteration

In [2]:
from datascience import *
import numpy as np

## Test statistics:

#### Definition: a test statistic allows us to decided whether the hypothesis test points in the direction of the null or alternative hypothesis.

Defintion of Null Hypothesis: this is a general statement or the deafault take on what should be happening for something. 

For example: If we were deciding whether a coin flip is fair or not, we would want the null hypothesis to be that the coin is fair (and that the number of tails is equal to the humber of heads, or that the probability of getting a head is 50%). Note there are many forms of a null hyptohesis. 

Defintion of Alternative Hypothesis: is contrary to the null hypothesis; used to test against the null hypothesis.

For example: If we are trying to test whether a coin flip is fair or not, our alternative hypothesis will be that the coin isn't fair (or that there are more tails than heads, or the probability of getting a tail is more than 50%). Note there are also many forms of an alternative hypothesis. 



#### Test Statistic and Choosing the Right One:

Notice how there are many forms of alternative and null hypotheses. This gives us many choices for a test statistic. 

In the coin flip example, we can choose one of many test statistics:
1. The number of heads in 10 coin flips. (Should be 5 if fair)
2. The number of tails in 10 coin flips. (Should be 5 if fair)
3. The proportion of heads in 10 coin flips. (Should be 0.5 if fair)
4. The proportion of tails in 10 coin flips. (Should be 0.5 if fair)
5. The number of heads minus the number of tails. (Should be 0 if fair)
6. 10 minus the number of heads. (Should be 5 if fair)
7. 10 minus the number of tails. (Should be 5 if fair)

## Hypothesis Testing:

In a hypothesis test, we will test to see which is true: the alternative or null hypothesis. We will do this by simulating samples for a certain number of times. Then we will compare the simulated statistic and the observed statistic and compute a p-value based on the comparisons. 

#### test #1:

Let's try to test whether a coin flip is fair or not for 10 flips. We will use number of heads as test statistic. 

Say we flip a coin ten times and get that nine heads show up. Then our observed statistic should be 9 because that is what he obsevre in the coin flip. 

In [4]:
observed_statistic = 9

But we say to ourselves, that getting 9 heads out of 10 is definitely weird becuase we should be getting around 5 if the coin is fair. Our null hypothesis is that the coin is fair, and the number of heads should be 5. Alternatively, the coin isn't fair and number of heads isn't (or isn't close to) 5. 

In [5]:
# we will sample 5000 times: 
# before sampling, a quick intro to for loop syntax which allows iteration:

#### For Loop Syntax

In a for loop, we have statement telling you to go through each element in an array and a body. The body tells you what to do for each element in the sequence:

```for item in array:
    body```
    
For example:
our array can be [1, 2, 3] and we can say

```for number in [1, 2, 3]:
    print(number)```

In [6]:
# running the print:
for number in [1, 2, 3]:
    print(number)

1
2
3


As we can see for every number in the array, it did something!

#### Back to sampling:

In [13]:
# we will need the range method
array = np.array(range(100))
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Range makes an array of items from 0 to n - 1 for the specified n in the range function.

In [17]:
# how to iterate using range:
for item in range(10): 
    print(item)

0
1
2
3
4
5
6
7
8
9


#### We will use this method of iterating through a range when sampling

In [30]:
# first try to get one simulated statistic, and then iterate!
sample_proportions(10, [0.6, 0.4])
# this will give us proportion of heads and tails, but we want a number of heads.

array([0.7, 0.3])

In [31]:
# We can take the first proportion to be that of heads, and multiply
# it by 10 to get number of heads
sample_proportions(10, [0.6, 0.4])[0] * 10

6.0

For the sample above, we got 6 heads out of 10 for that one time. Now we can iterate!

In [45]:
# we want to collect the simulated_statistic over the number of times we sample
# so we create an array to capture the simulated_statistic
simulated_statistic = make_array()
# now we iterate using range
for number in range(1000): # we will sample 1000 times
    statistic = sample_proportions(10, [0.5, 0.5])[0] * 10
    simulated_statistic = np.append(statistic, simulated_statistic)

In [46]:
simulated_statistic

array([ 5.,  5.,  4.,  6.,  4.,  6.,  6.,  6.,  6.,  6.,  6.,  5.,  4.,
        4.,  8.,  5.,  5.,  5.,  6.,  4.,  4.,  6.,  4.,  3.,  1.,  6.,
        8.,  1.,  5.,  6.,  3.,  4.,  5.,  7.,  6.,  6.,  3.,  5.,  6.,
        4.,  8.,  5.,  4.,  6.,  5.,  5.,  4.,  7.,  5.,  5.,  4.,  7.,
        4.,  4.,  5.,  8.,  5.,  5.,  5.,  6.,  7.,  4.,  5.,  4.,  4.,
        6.,  5.,  6.,  5.,  4.,  4.,  6.,  4.,  3.,  5.,  5.,  5.,  6.,
        3.,  6.,  4.,  6.,  4.,  7.,  6.,  0.,  2.,  4.,  3.,  6.,  7.,
        5.,  6.,  4.,  5.,  6.,  2.,  3.,  5.,  5.,  5.,  8.,  9.,  5.,
        5.,  5.,  6.,  7.,  4.,  4.,  6.,  4.,  4.,  7.,  7.,  4.,  5.,
        6.,  7.,  6.,  5.,  6.,  6.,  3.,  3.,  5.,  4.,  8.,  5.,  3.,
        5.,  4.,  4.,  4.,  6.,  4.,  3.,  7.,  2.,  6.,  5.,  7.,  4.,
        5.,  6.,  4.,  4.,  3.,  3.,  6.,  4.,  5.,  5.,  4.,  7.,  7.,
        6.,  6.,  7.,  3.,  2.,  6.,  5.,  3.,  7.,  5.,  5.,  4.,  4.,
        6.,  4.,  4.,  4.,  6.,  6.,  4.,  4.,  7.,  3.,  7.,  3

simulated_statistic represents our sample. Now we will check how many times its more than 9. 

In [47]:
simulated_statistic > observed_statistic

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [48]:
# to count the number of times its true, use either np.count_nonzero or sum:
sum(simulated_statistic > observed_statistic)

1

In [49]:
np.count_nonzero(simulated_statistic > observed_statistic)

1

In [50]:
# to find the p-value, take the count when the simulated statistic 
# is more than the observed and divide by the number of times samples
# were taken:
np.count_nonzero(simulated_statistic > observed_statistic)/1000

0.001

Our p-value is:   __0.001__

Now say we have an 